# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "worker1"
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
   config.vm.provision "shell", inline: <<-SHELL
     yum update
     yum install -y git
     git clone https://github.com/sandervanvugt/kubernetes
     cd kubernetes && swapoff -a 
   SHELL
end
