# -*- mode: ruby -*-
# vi: set ft=ruby :


# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control"
  
  config.vm.provider "virtualbox" do |vb|
  config.vm.network "private_network", ip: "192.168.33.12"
    vb.memory = "4096"
    vb.cpus = 2
  end
   config.vm.provision "shell", inline: <<-SHELL
     yum update
     yum install -y git
     git clone https://github.com/sandervanvugt/kubernetes
     cd kubernetes && swapoff -a 
   SHELL
end
